version: '3.4'
services:
    mcmap_nginx:
        container_name: mcmap_nginx
        image: nginx:1.21.4
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - ./code:/var/www/code
            - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        env_file:
            - .env
        links:
            - mcmap_php
        depends_on:
            - mysql
        logging:
            options:
                max-size: 10m
    mcmap_php:
        container_name: mcmap_php
        build: ./docker/php-fpm
        expose:
            - "9000"
        volumes:
            - ./code:/var/www/code
            - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        env_file:
            - .env
        links:
            - mysql
        depends_on:
            - mysql
        logging:
            options:
                max-size: 10m
    mysql:
        container_name: mcmap_mysql
        image: mysql:8.0.16
        ports:
            - "3307:3306"
        volumes:
            - ./docker/mysql/mysql-low-memory.cnf:/etc/mysql/conf.d/mysql-low-memory.cnf:ro
            - ./mysql:/var/lib/mysql
            - ./docker/mysql/mcmap.sql:/docker-entrypoint-initdb.d/mcmap.sql
        env_file: .env
        logging:
            options:
                max-size: 10m