INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/ba/Acacia_Boat_%28item%29_JE2_BE3.png','Acacia Boat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/af/Apple_JE3_BE3.png','Apple');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/25/Arrow_%28item%29_JE1_BE1.png','Arrow');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b7/Arrow_of_Decay_BE1.png','Arrow of Decay BE1');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a7/Arrow_of_Decay_BE2.png','Arrow of Decay BE2');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/48/Arrow_of_Fire_Resistance_JE1_BE1.png','Arrow of Fire Resistance');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/29/Arrow_of_Harming_JE1_BE1.png','Arrow of Harming');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4c/Arrow_of_Healing_JE1_BE1.png','Arrow of Healing');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1f/Arrow_of_Invisibility_JE1_BE1.png','Arrow of Invisibility');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/50/Arrow_of_Leaping_JE1_BE1.png','Arrow of Leaping');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ad/Arrow_of_Luck_JE1_BE1.png','Arrow of Luck');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1c/Arrow_of_Night_Vision_JE1_BE1.png','Arrow of Night Vision');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/be/Arrow_of_Poison_JE1_BE1.png','Arrow of Poison');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1b/Arrow_of_Regeneration_JE1_BE1.png','Arrow of Regeneration');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/eb/Arrow_of_Slow_Falling_JE1_BE1.png','Arrow of Slow Falling');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/92/Arrow_of_Slowness_JE1_BE1.png','Arrow of Slowness');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1c/Arrow_of_Strength_JE1_BE1.png','Arrow of Strength');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/00/Arrow_of_Swiftness_JE1_BE1.png','Arrow of Swiftness');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/01/Arrow_of_the_Turtle_Master_JE1_BE1.png','Arrow of the Turtle Master');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f2/Arrow_of_Water_Breathing_JE1_BE1.png','Arrow of Water Breathing');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4a/Arrow_of_Weakness_JE1_BE1.png','Arrow of Weakness');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e0/Baked_Potato_JE4_BE2.png','Baked Potato');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9e/Barrier_%28held%29_JE2_BE2.png','Barrier (held)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/80/Beetroot_Seeds_JE2_BE2.png','Beetroot Seeds');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6c/Beetroot_Soup_JE2_BE2.png','Beetroot Soup');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f4/Birch_Boat_%28item%29_JE2_BE3.png','Birch Boat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7c/Blaze_Powder_JE2_BE1.png','Blaze Powder');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/87/Blaze_Rod_JE1_BE1.png','Blaze Rod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8c/Blue_Sparkler_BE1.png','Blue Sparkler BE1');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3a/Bone_JE3_BE2.png','Bone');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b1/Bone_Meal_JE3_BE3.png','Bone Meal');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e9/Book_and_Quill_JE2_BE2.png','Book and Quill');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/50/Book_JE2_BE2.png','Book');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/34/Bow_%28Pull_0%29_BE2.png','Bow (Pull 0) BE2');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3b/Bow_%28Pull_0%29_JE1_BE1.png','Bow (Pull 0)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e0/Bow_%28Pull_1%29_BE2.png','Bow (Pull 1) BE2');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/14/Bow_%28Pull_1%29_JE1_BE1.png','Bow (Pull 1)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/20/Bow_%28Pull_2%29_BE2.png','Bow (Pull 2) BE2');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ab/Bow_%28Pull_2%29_JE1_BE1.png','Bow (Pull 2)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e5/Bow_JE1.png','Bow');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/99/Bow_JE2_BE1.png','Bow');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/82/Bowl_JE2_BE2.png','Bowl');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/29/Bread_JE2_BE2.png','Bread');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/44/Bread_JE3_BE3.png','Bread');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/32/Brick_JE2_BE2.png','Brick');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f7/Broken_Elytra_%28item%29_JE2_BE2.png','Broken Elytra');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fc/Bucket_JE2_BE2.png','Bucket');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/20/Bucket_of_Cod.png','Bucket of Cod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fc/Bucket_of_Pufferfish.png','Bucket of Pufferfish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c3/Bucket_of_Salmon.png','Bucket of Salmon');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/48/Bucket_of_Tropical_Fish.png','Bucket of Tropical Fish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/63/Buried_Treasure_Map_BE3.png','Buried Treasure Map BE3');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9a/Cake_%28item%29_JE3_BE3.png','Cake');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4e/Carrot_JE3_BE2.png','Carrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/12/Carrot_on_a_Stick_JE2_BE2.png','Carrot on a Stick');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/db/Cast_Fishing_Rod_JE3_BE2.png','Cast Fishing Rod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7a/Chainmail_Boots_%28item%29_JE1_BE1.png','Chainmail Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/22/Chainmail_Chestplate_%28item%29_JE1_BE1.png','Chainmail Chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0c/Chainmail_Helmet_%28item%29_JE1_BE1.png','Chainmail Helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/eb/Chainmail_Leggings_%28item%29_JE1_BE1.png','Chainmail Leggings');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a9/Charcoal_JE4_BE4.png','Charcoal');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/33/Chorus_Fruit_JE2_BE2.png','Chorus Fruit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/71/Clay_Ball_JE2_BE2.png','Clay Ball');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c4/Clock_JE1_BE2.png','Clock');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/58/Coal_JE4_BE3.png','Coal');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/85/Cocoa_Beans_JE4_BE3.png','Cocoa Beans');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7d/Compass_JE1_BE1.png','Compass');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/66/Cooked_Chicken_JE3_BE3.png','Cooked Chicken');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2e/Cooked_Cod_JE1_BE1.png','Cooked Cod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/53/Cooked_Cod_JE4_BE3.png','Cooked Cod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/00/Cooked_Mutton_JE2_BE1.png','Cooked Mutton');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7d/Cooked_Mutton_JE3_BE2.png','Cooked Mutton');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ee/Cooked_Porkchop_JE4_BE3.png','Cooked Porkchop');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9f/Cooked_Rabbit_JE2_BE1.png','Cooked Rabbit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2b/Cooked_Salmon_JE2_BE2.png','Cooked Salmon');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b3/Cookie_JE2_BE2.png','Cookie');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7c/Crimson_Roots_%28item%29_JE1.png','Crimson Roots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b2/Crimson_Sign_JE1_BE1.png','Crimson Sign');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/52/Cyan_Dye_JE2_BE2.png','Cyan Dye');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f7/Dark_Oak_Boat_%28item%29_JE2_BE3.png','Dark Oak Boat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ae/Diamond_Axe_JE2_BE2.png','Diamond Axe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f0/Diamond_Boots_%28item%29_JE1_BE1.png','Diamond Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e3/Diamond_Chestplate_%28item%29_JE1_BE1.png','Diamond Chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/73/Diamond_Helmet_%28item%29_JE1_BE1.png','Diamond Helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/68/Diamond_Hoe_JE2_BE2.png','Diamond Hoe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ab/Diamond_JE3_BE3.png','Diamond');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8e/Diamond_Leggings_%28item%29_JE1_BE1.png','Diamond Leggings');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7a/Diamond_Pickaxe_JE2_BE2.png','Diamond Pickaxe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/61/Diamond_Shovel_JE2_BE2.png','Diamond Shovel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6a/Diamond_Sword_JE2_BE2.png','Diamond Sword');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8a/Dragon%27s_Breath_JE2_BE2.png','Dragon''s Breath');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2a/Dried_Kelp_JE1.png','Dried Kelp');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/96/Egg_JE2_BE2.png','Egg');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/98/Elytra_%28item%29_JE2_BE2.png','Elytra');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/26/Emerald_JE3_BE3.png','Emerald');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ef/Enchanted_Book_JE2_BE2.png','Enchanted Book');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4c/Enchanted_Bow.gif','Enchanted Bow');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5e/Enchanted_Carrot_on_a_Stick.gif','Enchanted Carrot on a Stick');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/01/Enchanted_Chainmail_Boots_%28item%29.gif','Enchanted Chainmail Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9a/Enchanted_Chainmail_Chestplate_%28item%29.gif','Enchanted Chainmail Chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b7/Enchanted_Chainmail_Helmet_%28item%29.gif','Enchanted Chainmail Helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e1/Enchanted_Chainmail_Leggings_%28item%29.gif','Enchanted Chainmail Leggings');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/35/Enchanted_Crossbow.gif','Enchanted Crossbow');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3c/Enchanted_Diamond_Axe.gif','Enchanted Diamond Axe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Enchanted_Diamond_Boots_%28item%29.gif','Enchanted Diamond Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8a/Enchanted_Diamond_Chestplate_%28item%29.gif','Enchanted Diamond Chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c4/Enchanted_Diamond_Helmet_%28item%29.gif','Enchanted Diamond Helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/81/Enchanted_Diamond_Hoe.gif','Enchanted Diamond Hoe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/29/Enchanted_Diamond_Leggings_%28item%29.gif','Enchanted Diamond Leggings');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/13/Enchanted_Diamond_Pickaxe.gif','Enchanted Diamond Pickaxe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Enchanted_Diamond_Shovel.gif','Enchanted Diamond Shovel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d1/Enchanted_Diamond_Sword.gif','Enchanted Diamond Sword');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/45/Enchanted_Elytra_%28item%29.gif','Enchanted Elytra');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e0/Enchanted_Fishing_Rod.gif','Enchanted Fishing Rod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d4/Enchanted_Golden_Axe.gif','Enchanted Golden Axe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/41/Enchanted_Golden_Boots_%28item%29.gif','Enchanted Golden Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/87/Enchanted_Golden_Chestplate_%28item%29.gif','Enchanted Golden Chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/77/Enchanted_Golden_Helmet_%28item%29.gif','Enchanted Golden Helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d8/Enchanted_Golden_Hoe.gif','Enchanted Golden Hoe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8d/Enchanted_Golden_Leggings_%28item%29.gif','Enchanted Golden Leggings');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/dd/Enchanted_Golden_Pickaxe.gif','Enchanted Golden Pickaxe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e4/Enchanted_Golden_Shovel.gif','Enchanted Golden Shovel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ef/Enchanted_Golden_Sword.gif','Enchanted Golden Sword');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/bf/Enchanted_Iron_Axe.gif','Enchanted Iron Axe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6e/Enchanted_Iron_Boots_%28item%29.gif','Enchanted Iron Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/60/Enchanted_Iron_Chestplate_%28item%29.gif','Enchanted Iron Chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/77/Enchanted_Iron_Helmet_%28item%29.gif','Enchanted Iron Helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/35/Enchanted_Iron_Hoe.gif','Enchanted Iron Hoe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/ce/Enchanted_Iron_Leggings_%28item%29.gif','Enchanted Iron Leggings');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fd/Enchanted_Iron_Pickaxe.gif','Enchanted Iron Pickaxe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/af/Enchanted_Iron_Shovel.gif','Enchanted Iron Shovel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/de/Enchanted_Iron_Sword.gif','Enchanted Iron Sword');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b4/Enchanted_Leather_Boots_%28item%29.gif','Enchanted Leather Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/06/Enchanted_Leather_Cap_%28item%29.gif','Enchanted Leather Cap');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/91/Enchanted_Leather_Pants_%28item%29.gif','Enchanted Leather Pants');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9f/Enchanted_Leather_Tunic_%28item%29.gif','Enchanted Leather Tunic');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4c/Enchanted_Netherite_Axe.gif','Enchanted Netherite Axe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/23/Enchanted_Netherite_Boots_%28item%29.gif','Enchanted Netherite Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/bb/Enchanted_Netherite_Chestplate_%28item%29.gif','Enchanted Netherite Chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7c/Enchanted_Netherite_Helmet_%28item%29.gif','Enchanted Netherite Helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/63/Enchanted_Netherite_Hoe.gif','Enchanted Netherite Hoe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b6/Enchanted_Netherite_Leggings_%28item%29.gif','Enchanted Netherite Leggings');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/68/Enchanted_Netherite_Pickaxe.gif','Enchanted Netherite Pickaxe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/11/Enchanted_Netherite_Shovel.gif','Enchanted Netherite Shovel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/74/Enchanted_Netherite_Sword.gif','Enchanted Netherite Sword');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b7/Enchanted_Shears.gif','Enchanted Shears');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/79/Enchanted_Shield_%28item%29.gif','Enchanted Shield');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d0/Enchanted_Stone_Axe.gif','Enchanted Stone Axe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/90/Enchanted_Stone_Hoe.gif','Enchanted Stone Hoe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/62/Enchanted_Stone_Pickaxe.gif','Enchanted Stone Pickaxe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8a/Enchanted_Stone_Shovel.gif','Enchanted Stone Shovel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ed/Enchanted_Stone_Sword.gif','Enchanted Stone Sword');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/02/Enchanted_Trident_%28item%29.gif','Enchanted Trident');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d5/Enchanted_Turtle_Shell_%28item%29.gif','Enchanted Turtle Shell');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e0/Enchanted_Wooden_Axe.gif','Enchanted Wooden Axe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2e/Enchanted_Wooden_Hoe.gif','Enchanted Wooden Hoe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/64/Enchanted_Wooden_Pickaxe.gif','Enchanted Wooden Pickaxe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0d/Enchanted_Wooden_Shovel.gif','Enchanted Wooden Shovel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Enchanted_Wooden_Sword.gif','Enchanted Wooden Sword');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/73/End_Crystal_%28item%29_JE1_BE1.png','End Crystal');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f2/End_Crystal_%28item%29_JE2_BE2.png','End Crystal');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f6/Ender_Pearl_JE3_BE2.png','Ender Pearl');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7a/Eye_of_Ender_JE2_BE2.png','Eye of Ender');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e2/Feather_JE3_BE2.png','Feather');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3b/Fire_Charge_JE2_BE2.png','Fire Charge');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fd/Firework_Rocket_JE2_BE2.png','Firework Rocket');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/39/Firework_Star_JE1_BE1.png','Firework Star');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7f/Fishing_Rod_JE2_BE2.png','Fishing Rod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/94/Flint_and_Steel_JE4_BE2.png','Flint and Steel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/97/Flint_JE3_BE3.png','Flint');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fb/Glass_Bottle_JE2_BE2.png','Glass Bottle');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e7/Glistering_Melon_Slice_JE3_BE2.png','Glistering Melon Slice');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/25/Glowstone_Dust_JE2_BE2.png','Glowstone Dust');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8a/Gold_Ingot_JE4_BE2.png','Gold Ingot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3d/Gold_Nugget_JE3_BE2.png','Gold Nugget');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/54/Golden_Apple_JE2_BE2.png','Golden Apple');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e2/Golden_Axe_JE3_BE2.png','Golden Axe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8d/Golden_Boots_%28item%29_JE1_BE1.png','Golden Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/aa/Golden_Carrot_JE4_BE2.png','Golden Carrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f6/Golden_Chestplate_%28item%29_JE1_BE1.png','Golden Chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/69/Golden_Helmet_%28item%29_JE1_BE1.png','Golden Helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/22/Golden_Hoe_JE2_BE2.png','Golden Hoe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/39/Golden_Leggings_%28item%29_JE1_BE1.png','Golden Leggings');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d8/Golden_Pickaxe_JE3_BE2.png','Golden Pickaxe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c9/Golden_Shovel_JE3_BE2.png','Golden Shovel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/db/Golden_Sword_JE3_BE2.png','Golden Sword');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/05/Gray_Dye_JE2_BE2.png','Gray Dye');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d7/Green_Dye_JE3_BE3.png','Green Dye');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/78/Green_Sparkler_BE1.png','Green Sparkler BE1');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/Gunpowder_JE2_BE2.png','Gunpowder');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9b/Heart_of_the_Sea_JE1_BE2.png','Heart of the Sea');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/20/Hopper_%28item%29_JE3_BE2.png','Hopper');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c6/Ink_Sac_JE2_BE2.png','Ink Sac');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5e/Iron_Axe_JE5_BE2.png','Iron Axe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/88/Iron_Boots_%28item%29_JE1_BE1.png','Iron Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/eb/Iron_Chestplate_%28item%29_JE1_BE1.png','Iron Chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/30/Iron_Helmet_%28item%29_JE1_BE1.png','Iron Helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/ba/Iron_Hoe_JE2_BE2.png','Iron Hoe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/64/Iron_Ingot_JE1.png','Iron Ingot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/ff/Iron_Ingot_JE2_BE1.png','Iron Ingot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fc/Iron_Ingot_JE3_BE2.png','Iron Ingot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cf/Iron_Leggings_%28item%29_JE1_BE1.png','Iron Leggings');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d1/Iron_Pickaxe_JE3_BE2.png','Iron Pickaxe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/aa/Iron_Shovel_JE3_BE2.png','Iron Shovel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8e/Iron_Sword_JE2_BE2.png','Iron Sword');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6a/Item_Frame_%28item%29_JE2_BE2.png','Item Frame');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1d/Jungle_Boat_%28item%29_JE2_BE3.png','Jungle Boat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/09/Kelp_%28item%29_JE1_BE2.png','Kelp');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/89/Knowledge_Book_JE2.png','Knowledge Book');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/43/Lapis_Lazuli_JE2_BE2.png','Lapis Lazuli');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/74/Lava_Bucket_JE2_BE2.png','Lava Bucket');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1f/Lead_JE2_BE2.png','Lead');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b5/Leather_Boots_%28item%29_JE4_BE3.png','Leather Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c5/Leather_Cap_%28item%29_JE4_BE3.png','Leather Cap');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6d/Leather_JE2_BE2.png','Leather');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7f/Leather_Pants_%28item%29_JE4_BE3.png','Leather Pants');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/71/Leather_Tunic_%28item%29_JE4_BE3.png','Leather Tunic');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9e/Light_Gray_Dye_JE2_BE2.png','Light Gray Dye');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0f/Lime_Dye_JE2_BE2.png','Lime Dye');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/80/Lingering_Potion.png','Lingering Potion');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/34/Locked_Map_%28item%29_BE2.png','Locked Map');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/da/Lodestone_Compass_JE2.gif','Lodestone Compass');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/08/Magma_Cream_JE3_BE2.png','Magma Cream');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/81/Map_%28item%29_BE3.png','Map');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4a/Melon_Seeds_JE1_BE1.png','Melon Seeds');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f2/Melon_Slice_JE2_BE2.png','Melon Slice');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/ca/Milk_Bucket_JE2_BE2.png','Milk Bucket');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a5/Minecart_%28item%29_JE3_BE2.png','Minecart');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/bd/Minecart_with_Chest_%28item%29_JE2_BE2.png','Minecart with Chest');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6e/Minecart_with_Command_Block_%28item%29_BE1.png','Minecart with Command Block');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7a/Minecart_with_Command_Block_%28item%29_JE2_BE3.png','Minecart with Command Block');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f1/Minecart_with_Furnace_%28item%29_JE2.png','Minecart with Furnace');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9e/Minecart_with_Hopper_%28item%29_JE2_BE2.png','Minecart with Hopper');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d7/Minecart_with_TNT_%28item%29_JE2_BE2.png','Minecart with TNT');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e0/Mushroom_Stew_JE2_BE2.png','Mushroom Stew');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/47/Music_Disc_11_JE1_BE1.png','Music Disc 11');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/44/Music_Disc_Cat_JE1_BE1.png','Music Disc Cat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/05/Name_Tag_JE2_BE2.png','Name Tag');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1a/Nautilus_Shell_JE1_BE2.png','Nautilus Shell');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/49/Nether_Brick_JE2_BE2.png','Nether Brick');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/64/Nether_Quartz_JE2_BE2.png','Nether Quartz');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d0/Nether_Star_JE3_BE2.png','Nether Star');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b3/Nether_Star.gif','Nether Star');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cc/Netherite_Boots_%28item%29_JE2.png','Netherite Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fa/Netherite_Chestplate_%28item%29_JE2_BE1.png','Netherite Chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cb/Netherite_Helmet_%28item%29_JE2_BE1.png','Netherite Helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/78/Netherite_Leggings_%28item%29_JE2_BE1.png','Netherite Leggings');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/58/Oak_Boat_%28item%29_JE4_BE3.png','Oak Boat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/98/Oak_Sign.png','Oak Sign');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/dd/Ocean_Explorer_Map_BE3.png','Ocean Explorer Map BE3');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/dc/Orange_Dye_JE2_BE2.png','Orange Dye');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9e/Orange_Sparkler_BE1.png','Orange Sparkler BE1');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/70/Painting_JE2_BE2.png','Painting');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f2/Paper_JE2_BE2.png','Paper');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5c/Phantom_Membrane_JE2_BE2.png','Phantom Membrane');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/98/Pink_Dye_JE2_BE2.png','Pink Dye');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c0/Poisonous_Potato_JE3_BE2.png','Poisonous Potato');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7f/Popped_Chorus_Fruit_JE2_BE2.png','Popped Chorus Fruit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Potato_JE3_BE2.png','Potato');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e3/Prismarine_Crystals_JE2_BE2.png','Prismarine Crystals');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ac/Prismarine_Shard_JE2_BE2.png','Prismarine Shard');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/02/Pufferfish_%28item%29_JE5_BE2.png','Pufferfish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ac/Pumpkin_Pie_JE2_BE2.png','Pumpkin Pie');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2b/Pumpkin_Seeds_JE1_BE1.png','Pumpkin Seeds');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/da/Purple_Dye_JE2_BE2.png','Purple Dye');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7c/Purple_Sparkler_BE1.png','Purple Sparkler BE1');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e9/Quiver_JE1.png','Quiver');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3e/Rabbit_Hide_JE3_BE2.png','Rabbit Hide');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0c/Rabbit_Stew_JE3_BE2.png','Rabbit Stew');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c0/Rabbit%27s_Foot_JE3_BE2.png','Rabbit''s Foot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0f/Raw_Beef_JE4_BE3.png','Raw Beef');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/51/Raw_Chicken_JE3_BE3.png','Raw Chicken');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5f/Raw_Cod_JE1_BE1.png','Raw Cod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ef/Raw_Cod_JE4_BE2.png','Raw Cod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b8/Raw_Mutton_JE2_BE1.png','Raw Mutton');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f3/Raw_Mutton_JE3_BE2.png','Raw Mutton');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e0/Raw_Porkchop_JE3_BE3.png','Raw Porkchop');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a2/Raw_Rabbit_JE2_BE1.png','Raw Rabbit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/72/Raw_Rabbit_JE3_BE2.png','Raw Rabbit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/75/Raw_Salmon_JE2_BE2.png','Raw Salmon');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/59/Red_Dye_JE3_BE3.png','Red Dye');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b1/Red_Sparkler_BE1.png','Red Sparkler BE1');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e1/Redstone_Dust_JE2_BE2.png','Redstone Dust');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ac/Rotten_Flesh_JE3_BE2.png','Rotten Flesh');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/Ruby_JE1_BE1.png','Ruby');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/ba/Saddle_JE2_BE2.png','Saddle');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cc/Scute_JE1_BE1.png','Scute');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5a/Shears_JE2_BE2.png','Shears');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f5/Shulker_Shell_JE2_BE2.png','Shulker Shell');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d0/Slimeball_JE2_BE2.png','Slimeball');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2a/Snowball_JE3_BE3.png','Snowball');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/54/Spectral_Arrow_%28item%29_JE2.png','Spectral Arrow');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1a/Spider_Eye_JE2_BE2.png','Spider Eye');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2d/Spruce_Boat_%28item%29_JE2_BE3.png','Spruce Boat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/04/Steak_JE4_BE3.png','Steak');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7a/Stick_JE1_BE1.png','Stick');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/02/Stone_Axe_JE2_BE2.png','Stone Axe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c8/Stone_Hoe_JE2_BE2.png','Stone Hoe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c4/Stone_Pickaxe_JE2_BE2.png','Stone Pickaxe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6c/Stone_Shovel_JE2_BE2.png','Stone Shovel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b1/Stone_Sword_JE2_BE2.png','Stone Sword');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d0/Structure_Void_%28item%29_JE2.png','Structure Void');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8f/Studded_Boots_%28item%29_JE1.png','Studded Boots');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f9/Studded_Chestplate_%28item%29_JE1.png','Studded Chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/91/Studded_Helmet_%28item%29_JE1.png','Studded Helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9e/Studded_Leggings_%28item%29_JE1.png','Studded Leggings');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b7/Sugar_JE2_BE2.png','Sugar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/20/Tipped_Arrow_Revision_1.png','Tipped Arrow Revision 1');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2e/Totem_of_Undying_JE2_BE2.png','Totem of Undying');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ad/Tropical_Fish_JE2_BE2.png','Tropical Fish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4b/Uncraftable_Tipped_Arrow_Revision_1.png','Uncraftable Tipped Arrow Revision 1');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b8/Warped_Sign_JE1_BE1.png','Warped Sign');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/78/Water_Bottle_JE1_BE1.png','Water Bottle');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/dc/Water_Bucket_JE2_BE2.png','Water Bucket');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/75/Wheat_JE2_BE2.png','Wheat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/33/Wheat_Seeds_JE1_BE1.png','Wheat Seeds');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/56/Wooden_Axe_JE2_BE2.png','Wooden Axe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/63/Wooden_Hoe_JE2_BE2.png','Wooden Hoe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0b/Wooden_Pickaxe_JE2_BE2.png','Wooden Pickaxe');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/26/Wooden_Shovel_JE2_BE2.png','Wooden Shovel');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d5/Wooden_Sword_JE2_BE2.png','Wooden Sword');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8f/Woodland_Explorer_Map_BE3.png','Woodland Explorer Map BE3');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a8/Written_Book_JE2_BE2.png','Written Book');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2d/Yellow_Dye_JE2_BE2.png','Yellow Dye');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f3/Agent.png','Agent');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/dd/Aggressive_Panda_JE1_BE2.png','Aggressive Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/04/Alex.png','Alex');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b1/Anemone.png','Anemone');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/98/Angry_Wolf.png','Angry Wolf');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ee/Baby_Husk_Riding_Husk.png','Baby Husk Riding Husk');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d2/Baby_Panda_BE1.png','Baby Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/62/Baby_Zombie_Pigman_Riding_Zombie_Pigman.png','Baby Zombie Pigman Riding Zombie Pigman');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7e/Baby_Zombie_Riding_Cow.png','Baby Zombie Riding Cow');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/81/Baby_Zombie_Riding_Horse.png','Baby Zombie Riding Horse');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4a/Baby_Zombie_Riding_Ocelot.png','Baby Zombie Riding Ocelot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6f/Baby_Zombie_Riding_Panda.png','Baby Zombie Riding Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7e/Baby_Zombie_Riding_Pig.png','Baby Zombie Riding Pig');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e5/Baby_Zombie_Riding_Sheep.png','Baby Zombie Riding Sheep');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/13/Baby_Zombie_Riding_Spider.png','Baby Zombie Riding Spider');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/db/Baby_Zombie_Riding_Tuxedo_Cat.png','Baby Zombie Riding Tuxedo Cat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/92/Baby_Zombie_Riding_Zombie_Butcher.png','Baby Zombie Riding Zombie Butcher');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7d/Baby_Zombie_Riding_Zombie.png','Baby Zombie Riding Zombie');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f4/Bat_%28Hang%29_JE2_BE2.png','Bat (Hang)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/09/Bat.gif','Bat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ad/Bat.png','Bat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/47/Bee_%28angry%29.gif','Bee (angry)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/38/Bee_%28angry%29.png','Bee (angry)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7c/Bee_types.gif','Bee types');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/28/Bee_with_nectar_%28angry%29.gif','Bee with nectar (angry)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/33/Bee_with_nectar_%28angry%29.png','Bee with nectar (angry)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e5/Bee_with_nectar.gif','Bee with nectar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/54/Bee_with_nectar.png','Bee with nectar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/58/Bee.gif','Bee');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/56/Bee.png','Bee');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2f/Black_%26_White_Rabbit_JE3_BE2.png','Black & White Rabbit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f9/Black_Carpeted_Llama.png','Black Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cf/Black_Cat.png','Black Cat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d5/Black_Rabbit_JE2_BE2.png','Black Rabbit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5d/Black_Tang.png','Black Tang');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d0/Blaze_JE2.png','Blaze');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5a/Blaze.gif','Blaze');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/88/Blue_Carpeted_Llama.png','Blue Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9b/Blue_Dory.png','Blue Dory');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/75/Blue_Parrot.png','Blue Parrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a6/British_Shorthair_Cat.png','British Shorthair Cat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/04/Brown_Carpeted_Llama.png','Brown Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5b/Brown_Llama.png','Brown Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/05/Brown_Mooshroom_JE1_BE1.png','Brown Mooshroom');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7d/Brown_Panda_JE1_BE1.png','Brown Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8d/Brown_Rabbit_JE2_BE2.png','Brown Rabbit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/70/Brown_Trader_Llama.png','Brown Trader Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/16/Butterflyfish.png','Butterflyfish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b0/Calico_Cat.png','Calico Cat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/33/Cave_Spider_Jockey.png','Cave Spider Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a2/Cave_Spider_Wither_Jockey.png','Cave Spider Wither Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/60/Cave_Spider.png','Cave Spider');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9d/Charged_Creeper_Animation.png','Charged Creeper Animation');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b8/Charged_Creeper_JE1_BE1.png','Charged Creeper');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a8/Chicken_Husk_Jockey.png','Chicken Husk Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2c/Chicken_JE2_BE2.png','Chicken');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a0/Chicken_Jockey_with_Carved_Pumpkin.png','Chicken Jockey with Carved Pumpkin');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d3/Chicken_Jockey.png','Chicken Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/26/Chicken_Jungle_Zombie_Jockey.png','Chicken Jungle Zombie Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/de/Chicken_Plains_Zombie_Jockey.png','Chicken Plains Zombie Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/43/Chicken_Savanna_Zombie_Jockey.png','Chicken Savanna Zombie Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/bd/Chicken_Snowy_Zombie_Jockey.png','Chicken Snowy Zombie Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6f/Chicken_Swamp_Zombie_Jockey.png','Chicken Swamp Zombie Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4c/Chicken_Taiga_Zombie_Jockey.png','Chicken Taiga Zombie Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/29/Chicken_Zombie_Butcher_Jockey.png','Chicken Zombie Butcher Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d9/Chicken_Zombie_Farmer_Jockey.png','Chicken Zombie Farmer Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8c/Chicken_Zombie_Librarian_Jockey.png','Chicken Zombie Librarian Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/51/Chicken_Zombie_Nitwit_Jockey.png','Chicken Zombie Nitwit Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b6/Chicken_Zombie_Pigman_Jockey.png','Chicken Zombie Pigman Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f8/Chicken_Zombie_Priest_Jockey.png','Chicken Zombie Priest Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e3/Chicken_Zombie_Smith_Jockey.png','Chicken Zombie Smith Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b7/Cichlid.png','Cichlid');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/ca/Clownfish.png','Clownfish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/82/Cod_BE.gif','Cod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/66/Cod.gif','Cod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/41/Cod.png','Cod');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a5/Cotton_Candy_Betta.png','Cotton Candy');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/84/Cow.png','Cow');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4a/Creamy_Llama.png','Creamy Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b2/Creamy_Trader_Llama.png','Creamy Trader Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5b/Creeper_JE2_BE1.png','Creeper');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/58/Cyan_Carpeted_Llama.png','Cyan Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fe/Cyan_Parrot.png','Cyan Parrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/68/Dancing_Blue_Parrot.gif','Dancing Blue Parrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/18/Dancing_Cyan_Parrot.gif','Dancing Cyan Parrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/08/Dancing_Gray_Parrot.gif','Dancing Gray Parrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/ba/Dancing_Green_Parrot.gif','Dancing Green Parrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/28/Dancing_parrot_JE1.gif','Dancing parrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/42/Dancing_Red_Parrot.gif','Dancing Red Parrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/70/Dolphin.gif','Dolphin');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0b/Dolphin.png','Dolphin');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/95/Donkey.png','Donkey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/24/Dottyback.png','Dottyback');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e0/Drowned_Targeting.png','Drowned Targeting');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/bc/Drowned_Throwing_Trident.png','Drowned Throwing Trident');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/33/Drowned_with_Trident.png','Drowned with Trident');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/57/Drowned.png','Drowned');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/75/Elder_Guardian.gif','Elder Guardian');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a4/Elder_Guardian.png','Elder Guardian');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cb/Emperor_Red_Snapper.png','Emperor Red Snapper');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0a/Ender_Dragon.gif','Ender Dragon');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5a/Ender_Dragon.png','Ender Dragon');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7e/Enderman_%28holding_Grass_Block%29.png','Enderman (holding Grass Block)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c7/Enderman_Screaming.png','Enderman Screaming');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/28/Enderman.png','Enderman');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6e/Endermite.gif','Endermite');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cf/Endermite.png','Endermite');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/23/Evoker_with_Ominous_Banner.png','Evoker with Ominous Banner');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/73/Fox.png','Fox');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d5/Ghast_JE2_BE2.gif','Ghast');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3b/Ghast_JE2_BE2.png','Ghast');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a5/Goat_BE1.png','Goat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/82/Goatfish.png','Goatfish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2f/Gold_Rabbit_JE2_BE2.png','Gold Rabbit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c8/Gray_Carpeted_Llama.png','Gray Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/15/Gray_Llama.png','Gray Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/90/Gray_Parrot.png','Gray Parrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d3/Gray_Trader_Llama.png','Gray Trader Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9a/Green_Carpeted_Llama.png','Green Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a2/Green_Parrot.png','Green Parrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/94/Guardian.gif','Guardian');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fd/Guardian.png','Guardian');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e4/Husk_JE2_BE2.png','Husk');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9f/Husk_Targeting.png','Husk Targeting');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c0/Husk_with_Carved_Pumpkin.png','Husk with Carved Pumpkin');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f2/Illusioner_with_Ominous_Banner.png','Illusioner with Ominous Banner');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0d/Iron_Golem.png','Iron Golem');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/22/Killer_Bunny_JE5.png','Killer Bunny');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0f/Lazy_Panda_JE1_BE1.png','Lazy Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a1/Light_Blue_Carpeted_Llama.png','Light Blue Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/59/Light_Gray_Carpeted_Llama.png','Light Gray Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1f/Lime_Carpeted_Llama.png','Lime Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0b/Lying_down_Black_Cat_with_Red_Collar.png','Lying down Black Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/88/Lying_down_British_Shorthair_Cat_with_Red_Collar.png','Lying down British Shorthair Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/21/Lying_down_Calico_Cat_with_Red_Collar.png','Lying down Calico Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cd/Lying_down_Jellie_Cat_with_Red_Collar.png','Lying down Jellie Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/54/Lying_down_Persian_Cat_with_Red_Collar.png','Lying down Persian Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/71/Lying_down_Ragdoll_Cat_with_Red_Collar.png','Lying down Ragdoll Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/31/Lying_down_Red_Cat_with_Red_Collar.png','Lying down Red Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/21/Lying_down_Siamese_Cat_with_Red_Collar.png','Lying down Siamese Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a2/Lying_down_Tabby_Cat_with_Red_Collar.png','Lying down Tabby Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2a/Lying_down_Tuxedo_Cat_with_Red_Collar.png','Lying down Tuxedo Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/39/Lying_down_White_Cat_with_Red_Collar.png','Lying down White Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2a/Magenta_Carpeted_Llama.png','Magenta Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c8/Magma_Cube_Jumping.png','Magma Cube Jumping');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ed/Magma_Cube.png','Magma Cube');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a9/Moorish_Idol.png','Moorish Idol');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e7/Mule.png','Mule');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0d/Ocelot.png','Ocelot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f7/Orange_Carpeted_Llama.png','Orange Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a0/Orange-White_Glitter.png','Orange-White Glitter');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b6/Ornate_Butterfly.png','Ornate Butterfly');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/dc/Panda_JE1_BE1.png','Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d9/Panda_Rolling.gif','Panda Rolling');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1f/PandaJockey.png','PandaJockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7e/Parrotfish.png','Parrotfish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ec/Persian_Cat.png','Persian Cat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/00/Phantom_JE2_BE1.gif','Phantom');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7e/Phantom_JE2_BE1.png','Phantom');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1a/Pig_JE3_BE2.png','Pig');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/76/Piglin_Attacking_with_melee_weapon.png','Piglin Attacking with melee weapon');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/83/Piglin_celebrate_hunt_Revision_1.gif','Piglin celebrate hunt Revision 1');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/31/Piglin_celebrate_hunt_Revision_2.gif','Piglin celebrate hunt Revision 2');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e3/Piglin_with_Crossbow_targeting_JE.png','Piglin with Crossbow targeting JE');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d4/Piglin_with_Crossbow.png','Piglin with Crossbow');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6c/Piglin.png','Piglin');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/57/Pillager_with_Ominous_Banner.png','Pillager with Ominous Banner');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d7/Pink_Carpeted_Llama.png','Pink Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f2/Playful_Panda_JE1_BE1.png','Playful Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/85/Polar_Bear_Revision_1.png','Polar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/02/Pufferfish_BE.gif','Pufferfish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/78/Pufferfish_large.gif','Pufferfish large');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2e/Pufferfish_large.png','Pufferfish large');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/72/Pufferfish_medium.gif','Pufferfish medium');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cc/Pufferfish_medium.png','Pufferfish medium');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/45/Pufferfish_small.gif','Pufferfish small');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/66/Pufferfish_small.png','Pufferfish small');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/08/Purple_Carpeted_Llama.png','Purple Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/62/Queen_Angelfish.png','Queen Angelfish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/96/Ragdoll_Cat.png','Ragdoll Cat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a3/Ravager_JE1.png','Ravager');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9e/Ravager_Rider_%28Evoker%29.png','Ravager Rider (Evoker)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7c/Ravager_Rider_%28Vindicator%29.png','Ravager Rider (Vindicator)');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a4/Ravager_Rider.png','Ravager Rider');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fb/Red_Carpeted_Llama.png','Red Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d8/Red_Cat.png','Red Cat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/64/Red_Cichlid.png','Red Cichlid');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/03/Red_Lipped_Blenny.png','Red Lipped Blenny');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/ab/Red_Mooshroom_JE3_BE2.png','Red Mooshroom');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/de/Red_Parrot.png','Red Parrot');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d3/Red_Snapper.png','Red Snapper');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/56/Saddled_Pig_JE3_BE2.png','Saddled Pig');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/61/Saddled_Strider_JE1_BE1.gif','Saddled Strider');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/28/Salmon_BE.gif','Salmon');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d8/Salmon.gif','Salmon');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e0/Salmon.png','Salmon');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/06/Salt_%26_Pepper_Rabbit_JE2_BE2.png','Salt & Pepper Rabbit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/69/Sheared_Snow_Golem_JE2_BE2.png','Sheared Snow Golem');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5d/Sheared_White_Sheep.png','Sheared White Sheep');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/be/Shulker_Closed.png','Shulker Closed');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/06/Shulker.png','Shulker');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fe/Siamese_Cat.png','Siamese Cat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/22/Silverfish_JE1_BE1.gif','Silverfish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b8/Silverfish_JE1_BE1.png','Silverfish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/61/Sitting_Aggressive_Panda_BE.png','Sitting Aggressive Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9d/Sitting_Brown_Panda_BE.png','Sitting Brown Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/dd/Sitting_Drowned.png','Sitting Drowned');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ea/Sitting_Enderman.png','Sitting Enderman');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6a/Sitting_Fox.png','Sitting Fox');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/22/Sitting_Husk.png','Sitting Husk');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cd/Sitting_Lazy_Panda_BE.png','Sitting Lazy Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f3/Sitting_Panda_BE.png','Sitting Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/60/Sitting_Playful_Panda_BE.png','Sitting Playful Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/16/Sitting_Skeleton.png','Sitting Skeleton');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1a/Sitting_Snow_Fox.png','Sitting Snow Fox');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/63/Sitting_Stray.png','Sitting Stray');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/26/Sitting_Weak_Panda_BE.png','Sitting Weak Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9c/Sitting_Wither_Skeleton.png','Sitting Wither Skeleton');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/75/Sitting_Worried_Panda_BE.png','Sitting Worried Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/15/Sitting_Zombie_Pigman.png','Sitting Zombie Pigman');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7f/Sitting_Zombie.png','Sitting Zombie');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/12/Skeleton_Aiming.png','Skeleton Aiming');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/56/Skeleton_in_leather_armor.png','Skeleton in leather armor');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/29/Skeleton_Trap.png','Skeleton Trap');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e3/Skeleton_with_Carved_Pumpkin.png','Skeleton with Carved Pumpkin');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/23/Skeleton.png','Skeleton');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/dd/Slime_JE3_BE2.png','Slime');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/bf/Snow_Fox.png','Snow Fox');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c2/Snow_Golem.png','Snow Golem');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1f/Spider_JE4_BE3.png','Spider');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ee/Spider_Jockey.png','Spider Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e1/Spider_Wither_Jockey.png','Spider Wither Jockey');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/ce/Squid.gif','Squid');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/81/Squid.png','Squid');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f3/Steve.png','Steve');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/89/Stray_Aiming_JE2_BE4.png','Stray Aiming');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/38/Stray_JE2_BE4.png','Stray');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/00/Strider_JE1_BE1.gif','Strider');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b3/Tabby_Cat.png','Tabby Cat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6f/Tamed_Black_Cat_with_Red_Collar.png','Tamed Black Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5d/Tamed_British_Shorthair_Cat_with_Red_Collar.png','Tamed British Shorthair Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d5/Tamed_Calico_Cat_with_Red_Collar.png','Tamed Calico Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/85/Tamed_Persian_Cat_with_Red_Collar.png','Tamed Persian Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9a/Tamed_Ragdoll_Cat_with_Red_Collar.png','Tamed Ragdoll Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4f/Tamed_Red_Cat_with_Red_Collar.png','Tamed Red Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9f/Tamed_Siamese_Cat_with_Red_Collar.png','Tamed Siamese Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a7/Tamed_Tabby_Cat_with_Red_Collar.png','Tamed Tabby Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/32/Tamed_Tuxedo_Cat_with_Red_Collar.png','Tamed Tuxedo Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e2/Tamed_White_Cat_with_Red_Collar.png','Tamed White Cat with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e0/Tamed_Wolf_with_Red_Collar.png','Tamed Wolf with Red Collar');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/94/Threadfin.png','Threadfin');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/93/Toast_Rabbit_JE2_BE2.png','Toast Rabbit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/96/Tomato_Clownfish.png','Tomato Clownfish');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e9/Turtle.png','Turtle');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a7/Tuxedo_Cat_Revision_2.png','Tuxedo Cat Revision 2');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b5/Vex_attacking.png','Vex attacking');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4f/Vex.gif','Vex');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/bc/Vex.png','Vex');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/74/Vindicator_with_Ominous_Banner.png','Vindicator with Ominous Banner');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/37/Weak_Panda_JE1_BE1.png','Weak Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/27/White_Carpeted_Llama.png','White Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3a/White_Cat.png','White Cat');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/43/White_Llama.png','White Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5e/White_Rabbit_JE2_BE2.png','White Rabbit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a5/White_Trader_Llama.png','White Trader Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/72/Wither_Skeleton_with_Carved_Pumpkin.png','Wither Skeleton with Carved Pumpkin');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cd/Wither_Skeleton.png','Wither Skeleton');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/aa/Wither.png','Wither');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c8/Wolf.png','Wolf');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/db/Worried_Panda_JE1_BE1.png','Worried Panda');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6b/Yellow_Carpeted_Llama.png','Yellow Carpeted Llama');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c4/Yellow_Tang.png','Yellow Tang');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cf/Zombie_Blacksmith.png','Zombie Blacksmith');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/be/Zombie_Butcher.png','Zombie Butcher');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1f/Zombie_chestplate.png','Zombie chestplate');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e8/Zombie_Farmer.png','Zombie Farmer');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5d/Zombie_full_set.png','Zombie full set');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/54/Zombie_helmet.png','Zombie helmet');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1f/Zombie_Horse_Revision_3.png','Zombie Horse Revision 3');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/dd/Zombie_in_chainmail_armor.png','Zombie in chainmail armor');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9c/Zombie_in_diamond_armor.png','Zombie in diamond armor');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/70/Zombie_in_golden_armor.png','Zombie in golden armor');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5c/Zombie_in_iron_armor.png','Zombie in iron armor');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3e/Zombie_in_leather_armor.png','Zombie in leather armor');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/34/Zombie_Librarian.png','Zombie Librarian');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9a/Zombie_Nitwit.png','Zombie Nitwit');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7d/Zombie_Pigman_Targeting.png','Zombie Pigman Targeting');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c9/Zombie_Pigman_with_Carved_Pumpkin.png','Zombie Pigman with Carved Pumpkin');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/26/Zombie_Priest.png','Zombie Priest');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d6/Zombie_Targeting.png','Zombie Targeting');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/76/Zombie_Villager_with_Carved_Pumpkin.png','Zombie Villager with Carved Pumpkin');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/13/Zombie_with_Carved_Pumpkin.png','Zombie with Carved Pumpkin');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c3/Zombie.png','Zombie');
INSERT INTO icons(url,name) VALUES ('https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e9/Zombified_Piglin_JE5.png','Zombified Piglin');
