version: '3.4'
services:
    nginx:
        container_name: mcmap_nginx
        image: nginx:latest
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - ../code:/var/www/code
            - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs:/var/log/nginx
        env_file:
            - .env
        links:
            - php-fpm
        depends_on:
            - mysql
        logging:
            options:
                max-size: 10m
    php-fpm:
        container_name: mcmap_php-fpm
        build: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ../code:/var/www/code
            - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        env_file:
            - .env
        links:
            - mysql
        depends_on:
            - mysql
        logging:
            options:
                max-size: 10m
    mysql:
        container_name: mcmap_mysql
        image: mysql:8.0.16
        ports:
            - "3307:3306"
        volumes:
            - ../mysql:/var/lib/mysql
            - ./mysql/mcmap.sql:/docker-entrypoint-initdb.d/mcmap.sql
        env_file: .env
        logging:
            options:
                max-size: 10m