version: '3.4'
services:
    nginx:
        container_name: mcmap_nginx
        image: nginx:latest
        ports:
            - "8083:80"
            - "4001:443"
        build:
            context: ../
            dockerfile: docker/nginx/prod/Dockerfile
        volumes:
            - ../code/public/minedmap/data:/var/www/code/public/minedmap/data
        env_file:
            - .env
        links:
            - php-fpm
        depends_on:
            - mysql
        restart: unless-stopped
        logging:
            options:
                max-size: 10m
    php-fpm:
        container_name: mcmap_php-fpm
        build:
            context: ../
            dockerfile: docker/php-fpm/prod/Dockerfile
        expose:
            - "9000"
        env_file:
            - .env
        links:
            - mysql
        depends_on:
            - mysql
        restart: unless-stopped
        logging:
            options:
                max-size: 10m
    mysql:
        container_name: mcmap_mysql
        image: mysql:5.7.22
        expose:
            - "3306"
        env_file: .env
        restart: unless-stopped
        logging:
            options:
                max-size: 10m
